// Иконки с надёжного CDN
const LOGOS = {
  spotify:  `<img src="https://cdn.simpleicons.org/spotify/1ED760" alt="Spotify">`,
  netflix:  `<img src="https://cdn.simpleicons.org/netflix/E50914" alt="Netflix">`,
  youtube:  `<img src="https://cdn.simpleicons.org/youtube/FF0000" alt="YouTube">`,
  chatgpt:  `<img src="https://cdn.simpleicons.org/openai/74aa9c" alt="ChatGPT">`,
  adobe:    `<img src="https://cdn.simpleicons.org/adobe/FF0000" alt="Adobe">`,
  canva:    `<img src="https://cdn.simpleicons.org/canva/00C4CC" alt="Canva">`,
  notion:   `<img src="https://cdn.simpleicons.org/notion/ffffff" alt="Notion">`,
  figma:    `<img src="https://cdn.simpleicons.org/figma/F24E1E" alt="Figma">`,
  duolingo: `<img src="https://cdn.simpleicons.org/duolingo/58CC02" alt="Duolingo">`,
};

const SERVICES = [
  {
    id: "spotify",
    name: "Spotify",
    category: "music",
    color: "#1ED760",
    bgGradient: "linear-gradient(135deg, #0f3d1e 0%, #051a0d 100%)",
    logo: LOGOS.spotify,
    badge: "Хит",
    shortDesc: "Музыка без границ",
    fullDesc: "Более 100 млн треков, подкасты и аудиокниги. Слушай без рекламы в отличном качестве.",
    features: ["100+ млн треков", "Скачивание офлайн", "Без рекламы", "Высокое качество звука"],
    plans: [
      { id: "1m", name: "1 месяц", priceRub: 299, popular: false },
      { id: "3m", name: "3 месяца", priceRub: 799, origRub: 897, popular: true },
      { id: "12m", name: "12 месяцев", priceRub: 2499, origRub: 3588, popular: false },
    ],
    payNote: "Доступ активируется в течение 15 минут",
  },
  {
    id: "netflix",
    name: "Netflix",
    category: "streaming",
    color: "#E50914",
    bgGradient: "linear-gradient(135deg, #3d0000 0%, #1a0000 100%)",
    logo: LOGOS.netflix,
    badge: "Топ",
    shortDesc: "Фильмы и сериалы",
    fullDesc: "Тысячи фильмов, сериалов и документальных проектов в 4K качестве.",
    features: ["4K Ultra HD", "До 4 экранов", "Загрузка контента", "Оригинальные проекты"],
    plans: [
      { id: "1m", name: "1 месяц", priceRub: 499, popular: false },
      { id: "3m", name: "3 месяца", priceRub: 1399, origRub: 1497, popular: true },
      { id: "12m", name: "12 месяцев", priceRub: 4999, origRub: 5988, popular: false },
    ],
    payNote: "Отправим данные для входа",
  },
  {
    id: "youtube",
    name: "YouTube Premium",
    category: "streaming",
    color: "#FF0000",
    bgGradient: "linear-gradient(135deg, #3d0000 0%, #1a0000 100%)",
    logo: LOGOS.youtube,
    badge: null,
    shortDesc: "YouTube без рекламы",
    fullDesc: "Смотри YouTube без рекламы, скачивай видео и слушай фоновое воспроизведение.",
    features: ["Без рекламы", "Фоновое воспроизведение", "Скачивание видео", "YouTube Music включён"],
    plans: [
      { id: "1m", name: "1 месяц", priceRub: 349, popular: false },
      { id: "3m", name: "3 месяца", priceRub: 949, origRub: 1047, popular: true },
      { id: "12m", name: "12 месяцев", priceRub: 3299, origRub: 4188, popular: false },
    ],
    payNote: "Подписка оформляется на ваш аккаунт",
  },
  {
    id: "chatgpt",
    name: "ChatGPT Plus",
    category: "ai",
    color: "#74aa9c",
    bgGradient: "linear-gradient(135deg, #0d2d26 0%, #051a14 100%)",
    logo: LOGOS.chatgpt,
    badge: "AI",
    shortDesc: "GPT-4 без ограничений",
    fullDesc: "Доступ к GPT-4o, DALL·E 3, Advanced Data Analysis и приоритетный доступ без очередей.",
    features: ["GPT-4o доступ", "DALL·E 3 генерация", "Анализ данных", "Приоритетный доступ"],
    plans: [
      { id: "1m", name: "1 месяц", priceRub: 1799, popular: false },
      { id: "3m", name: "3 месяца", priceRub: 4999, origRub: 5397, popular: true },
      { id: "12m", name: "12 месяцев", priceRub: 17999, origRub: 21588, popular: false },
    ],
    payNote: "Потребуется аккаунт OpenAI",
  },
  {
    id: "adobe",
    name: "Adobe Creative",
    category: "tools",
    color: "#FF0000",
    bgGradient: "linear-gradient(135deg, #3d0000 0%, #1a0000 100%)",
    logo: LOGOS.adobe,
    badge: "Pro",
    shortDesc: "Photoshop, Illustrator и др.",
    fullDesc: "Полный доступ к Adobe Creative Cloud: Photoshop, Illustrator, Premiere Pro и 20+ приложений.",
    features: ["20+ приложений", "100 ГБ облако", "Adobe Fonts", "Обновления включены"],
    plans: [
      { id: "1m", name: "1 месяц", priceRub: 2499, popular: false },
      { id: "3m", name: "3 месяца", priceRub: 6999, origRub: 7497, popular: true },
      { id: "12m", name: "12 месяцев", priceRub: 24999, origRub: 29988, popular: false },
    ],
    payNote: "Нужен Adobe ID",
  },
  {
    id: "canva",
    name: "Canva Pro",
    category: "tools",
    color: "#00C4CC",
    bgGradient: "linear-gradient(135deg, #003d3f 0%, #001a1b 100%)",
    logo: LOGOS.canva,
    badge: null,
    shortDesc: "Дизайн для всех",
    fullDesc: "Профессиональные шаблоны, удаление фона, планировщик соцсетей и 100 ГБ хранилища.",
    features: ["100 млн+ шаблонов", "Удаление фона", "Планировщик SMM", "Брендбук"],
    plans: [
      { id: "1m", name: "1 месяц", priceRub: 699, popular: false },
      { id: "3m", name: "3 месяца", priceRub: 1899, origRub: 2097, popular: true },
      { id: "12m", name: "12 месяцев", priceRub: 6499, origRub: 8388, popular: false },
    ],
    payNote: "Активация в течение часа",
  },
  {
    id: "notion",
    name: "Notion Plus",
    category: "tools",
    color: "#ffffff",
    bgGradient: "linear-gradient(135deg, #1a1a1a 0%, #0d0d0d 100%)",
    logo: LOGOS.notion,
    badge: null,
    shortDesc: "База знаний и задачи",
    fullDesc: "Неограниченные блоки, версионирование, гостевой доступ и интеграции для команд.",
    features: ["Без лимита блоков", "История версий", "Гостевой доступ", "API интеграции"],
    plans: [
      { id: "1m", name: "1 месяц", priceRub: 599, popular: false },
      { id: "3m", name: "3 месяца", priceRub: 1599, origRub: 1797, popular: true },
      { id: "12m", name: "12 месяцев", priceRub: 5499, origRub: 7188, popular: false },
    ],
    payNote: "Потребуется Notion аккаунт",
  },
  {
    id: "figma",
    name: "Figma Professional",
    category: "tools",
    color: "#F24E1E",
    bgGradient: "linear-gradient(135deg, #3d1200 0%, #1a0800 100%)",
    logo: LOGOS.figma,
    badge: null,
    shortDesc: "Дизайн интерфейсов",
    fullDesc: "Неограниченные проекты, командные библиотеки, продвинутые прототипы и история версий.",
    features: ["Неограниченные проекты", "Командные библиотеки", "Прототипирование", "История версий"],
    plans: [
      { id: "1m", name: "1 месяц", priceRub: 799, popular: false },
      { id: "3m", name: "3 месяца", priceRub: 2199, origRub: 2397, popular: true },
      { id: "12m", name: "12 месяцев", priceRub: 7999, origRub: 9588, popular: false },
    ],
    payNote: "Нужен Figma аккаунт",
  },
  {
    id: "duolingo",
    name: "Duolingo Super",
    category: "tools",
    color: "#58CC02",
    bgGradient: "linear-gradient(135deg, #1a3d00 0%, #0d1f00 100%)",
    logo: LOGOS.duolingo,
    badge: null,
    shortDesc: "Изучение языков",
    fullDesc: "Без рекламы, неограниченные жизни, офлайн уроки и персонализированная практика.",
    features: ["Без рекламы", "Неограниченные жизни", "Офлайн уроки", "Персонализация"],
    plans: [
      { id: "1m", name: "1 месяц", priceRub: 249, popular: false },
      { id: "3m", name: "3 месяца", priceRub: 649, origRub: 747, popular: true },
      { id: "12m", name: "12 месяцев", priceRub: 1999, origRub: 2988, popular: false },
    ],
    payNote: "Активируется через ваш аккаунт Duolingo",
  },
];

function formatPrice(rub) {
  return rub.toLocaleString('ru-RU') + ' ₽';
}
